/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import kotlin.concurrent.thread

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    thread(start = true) { Producer.runProducer() }
    thread(start = true) { Consumer.runConsumer() }

    // Prevent main thread from exiting
    Thread.sleep(1500)
}
